name: EC530 Trevor Chan
run-name: Perform Python Tests
on: [push]
jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Download Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: flake8 lint
        run: |
          flake8 ../..
        continue-on-error: true

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Download Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Download Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest 
      - name: Run pytest
        run: |
          python -m pytest ../..