name: EC530 Trevor Chan
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Check out the repo"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Job status - ${{ job.status }}."
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Download Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1
          architecture: x64
      - name: Install Dependencies
        run: pip install flake8 pytest
      - name: flake8 lint
        run: flake8